Wakeel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    ]

urlpatterns += i18n_patterns(
    path('', include('clients.urls'), name='client'),
    path('', include('contracts.urls'), name='contract'),
    path('', include('documents.urls'), name='document'),
    path('', include('projects.urls'), name='project'),
    path('', include('proposals.urls'), name='proposal'),
    path('', include('users.urls'), name='user'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import client_list, client_view, client_create, client_update, \
    client_delete, proposal_client_create, pdf_generation_client

app_name = 'client'

urlpatterns = [

    path('client/list/', client_list, name='client_list'),
    path('client/view/<int:id>/', client_view, name='client_view'),
    path('client/create/', client_create, name='client_create'),
    path('client/update/<int:id>/', client_update, name='client_update'),
    path('client/delete/<int:id>/', client_delete, name='client_delete'),

    path('client/pdf/<int:id>', pdf_generation_client, name='client_pdf'),

    path('client/proposal/<int:id>/', proposal_client_create, name='proposal_client_create'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contracts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import contract_list, contract_view, contract_create, contract_update, contract_delete, \
    pdf_generation_contract, contract_project_create
app_name = 'contract'

urlpatterns = [
 

    path('contract/list/', contract_list, name='contract_list'),
    path('contract/view/<int:id>/', contract_view, name='contract_view'),
    path('contract/create/', contract_create, name='contract_create'),
    path('contract/update/<int:id>/', contract_update, name='contract_update'),
    path('contract/delete/<int:id>/', contract_delete, name='contract_delete'),

    path('contract/pdf/<int:id>', pdf_generation_contract, name='contract_pdf'),
    path('project/contract/<int:id>/', contract_project_create, name='contract_project_create'),
   

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import document_list, document_view, document_create, document_update, document_delete,\
    pdf_generation, document_task_create
app_name = 'document'


urlpatterns = [

    path('document/list/', document_list, name='document_list'),
    path('document/view/<int:id>/', document_view, name='document_view'),
    path('document/create/', document_create, name='document_create'),
    path('document/update/<int:id>/', document_update, name='document_update'),
    path('document/delete/<int:id>/', document_delete, name='document_delete'),

    path('document/pdf/<int:id>', pdf_generation, name='document_pdf'),
    path('task/document/<int:id>/', document_task_create, name='document_task_create'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import project_list, project_view, project_create, project_update, project_delete, task_project_create, \
    pdf_generation_project, task_list, task_view, task_create, task_update, task_delete, pdf_generation_task

app_name = 'project'

urlpatterns = [

    path('project/list/', project_list, name='project_list'),
    path('project/view/<int:id>/', project_view, name='project_view'),
    path('project/create/', project_create, name='project_create'),
    path('project/update/<int:id>/', project_update, name='project_update'),
    path('project/delete/<int:id>/', project_delete, name='project_delete'),

    path('project/pdf/<int:id>', pdf_generation_project, name='project_pdf'),
    path('project/task/<int:id>/', task_project_create, name='task_project_create'),

    path('task/list/', task_list, name='task_list'),
    path('task/view/<int:id>/', task_view, name='task_view'),
    path('task/create/', task_create, name='task_create'),
    path('task/update/<int:id>/', task_update, name='task_update'),
    path('task/delete/<int:id>/', task_delete, name='task_delete'),

    path('task/pdf/<int:id>', pdf_generation_task, name='task_pdf'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import loginPage, logoutUser, dashboard_with_pivot, pivot_data

app_name = 'user'

urlpatterns = [
    # path('home/', dashboard, name='dashboard'),

    # path('register/', views.registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),

    # Password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_done.html"),
         name="password_reset_complete"),

    path('', dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', pivot_data, name='pivot_data'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

users/views.py
from base64 import urlsafe_b64encode
from collections import UserString
from email import quoprimime

from clients.models import Client
from contracts.models import Contract
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core import serializers
from django.core.mail import send_mail
from django.http import BadHeaderError, HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils import translation
from django.utils.encoding import force_bytes
from documents.models import Document
from projects.models import Project
from proposals.models import Proposal
from projects.models import Task
from users.decorators import unauthenticated_user


# Create your views here.


# def dashboard(request):
#     return render(request, 'dashboard.html')


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = UserString.objects.filter(
                quoprimime(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "main/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_b64encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="main/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('/login')


# Language

def selectlanguage(request):
    if request.method == 'POST':  # check post
        cur_language = translation.get_language()
        lasturl = request.META.get('HTTP_REFERER')
        lang = request.POST['language']
        translation.activate(lang)
        request.session[translation.LANGUAGE_SESSION_KEY] = lang
        # return HttpResponse(lang)
        return HttpResponseRedirect("" + lang)


# Report
def dashboard_with_pivot(request):
    return render(request, 'dashboard_with_pivot.html', {})


def pivot_data(request):
    dataset = [*Client.objects.all(), *Proposal.objects.all(), *Contract.objects.all(), *Project.objects.all(),
               *Task.objects.all(), *Document.objects.all()]
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

users/templates/base.html
{% load static %}
{% load i18n %}
{%if LANGUAGE_CODE == 'ar'%}
<html lang="ar" dir="rtl">
{% else %}
<html lang="en">
{% endif %}


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" media="all">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" media="all">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{#        <link href="{% static 'css/style.css' %}" rel="stylesheet">#}

    <title>factory system</title>

</head>
<body>




{% include 'menu1.html' %}
<form action="/i18n/setlang/" method="post">
<input name="next" type="hidden" value="/next/page/" />
<select name="language">
    {% for lang in LANGUAGES %}
    <option value="{{ lang.0 }}">{{ lang.1 }}</option>
    {% endfor %}
</select>
<input type="submit" value="Go" />
</form>
    <div class="container-fluid" >
      <div class="row">
              {% block content %} {% endblock %}

          </div><!-- /.col -->
    </div>


<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

users/templates/dashboard.html
{% load static  %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.84.0">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <style type="text/css">/* Chart.js */
    @keyframes chartjs-render-animation {
        from {
            opacity: .99
        }
        to {
            opacity: 1
        }
    }

    .chartjs-render-monitor {
        animation: chartjs-render-animation 1ms
    }

    .chartjs-size-monitor, .chartjs-size-monitor-expand, .chartjs-size-monitor-shrink {
        position: absolute;
        direction: ltr;
        left: 0;
        top: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        pointer-events: none;
        visibility: hidden;
        z-index: -1
    }

    .chartjs-size-monitor-expand > div {
        position: absolute;
        width: 1000000px;
        height: 1000000px;
        left: 0;
        top: 0
    }

    .chartjs-size-monitor-shrink > div {
        position: absolute;
        width: 200%;
        height: 200%;
        left: 0;
        top: 0
    }</style>
</head>
<body>

{% include 'menu1.html' %}

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="chartjs-size-monitor">
                <div class="chartjs-size-monitor-expand">
                    <div class=""></div>
                </div>
                <div class="chartjs-size-monitor-shrink">
                    <div class=""></div>
                </div>
            </div>
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Dashboard</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">
                        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                    </div>
                    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-calendar" aria-hidden="true">
                            <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                            <line x1="16" y1="2" x2="16" y2="6"></line>
                            <line x1="8" y1="2" x2="8" y2="6"></line>
                            <line x1="3" y1="10" x2="21" y2="10"></line>
                        </svg>
                        This week
                    </button>
                </div>
            </div>

            <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="720" height="304"
                    style="display: block; width: 720px; height: 304px;"></canvas>

                    <img src="{% static 'images/pie-chart-example-1.png' %}" style="width:45%">

                    <img src="{% static 'images/basic-bar-graph.png' %}" style="width:45%">


{#            <h2>Section title</h2>#}
{#            <div class="table-responsive">#}
{#                <table class="table table-striped table-sm">#}
{#                    <thead>#}
{#                    <tr>#}
{#                        <th scope="col">#</th>#}
{#                        <th scope="col">Header</th>#}
{#                        <th scope="col">Header</th>#}
{#                        <th scope="col">Header</th>#}
{#                        <th scope="col">Header</th>#}
{#                    </tr>#}
{#                    </thead>#}
{#                    <tbody>#}
{#                    <tr>#}
{#                        <td>1,001</td>#}
{#                        <td>random</td>#}
{#                        <td>data</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>text</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,002</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>irrelevant</td>#}
{#                        <td>visual</td>#}
{#                        <td>layout</td>#}
{#                    </tr>#}
{#                 #}
{#                    <tr>#}
{#                        <td>1,005</td>#}
{#                        <td>dashboard</td>#}
{#                        <td>irrelevant</td>#}
{#                        <td>text</td>#}
{#                        <td>placeholder</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,006</td>#}
{#                        <td>dashboard</td>#}
{#                        <td>illustrative</td>#}
{#                        <td>rich</td>#}
{#                        <td>data</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,007</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>tabular</td>#}
{#                        <td>information</td>#}
{#                        <td>irrelevant</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,008</td>#}
{#                        <td>random</td>#}
{#                        <td>data</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>text</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,009</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>irrelevant</td>#}
{#                        <td>visual</td>#}
{#                        <td>layout</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,010</td>#}
{#                        <td>data</td>#}
{#                        <td>rich</td>#}
{#                        <td>dashboard</td>#}
{#                        <td>tabular</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,011</td>#}
{#                        <td>information</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>illustrative</td>#}
{#                        <td>data</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,012</td>#}
{#                        <td>text</td>#}
{#                        <td>placeholder</td>#}
{#                        <td>layout</td>#}
{#                        <td>dashboard</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,013</td>#}
{#                        <td>dashboard</td>#}
{#                        <td>irrelevant</td>#}
{#                        <td>text</td>#}
{#                        <td>visual</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,014</td>#}
{#                        <td>dashboard</td>#}
{#                        <td>illustrative</td>#}
{#                        <td>rich</td>#}
{#                        <td>data</td>#}
{#                    </tr>#}
{#                    <tr>#}
{#                        <td>1,015</td>#}
{#                        <td>random</td>#}
{#                        <td>tabular</td>#}
{#                        <td>information</td>#}
{#                        <td>text</td>#}
{#                    </tr>#}


                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>


<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="{% static 'dashboardJs/dashboard.js' %}"></script>


</body>
</html>

users/templates/header.html
{% load static %}
{% load i18n %}

{% block content %}


  {% block custom_css %}
        <style type="text/css" media="all">
            @media print {
                @page {
                    size: 5.5in 8.5in;
                    size: landscape;


                }

                #btnPrint {
                    display: none !important;
                }

                body {
                    height: 100%;
                    width: 100%;
                }



  .row {
                display: flex;
                margin-left: -5px;
                margin-right: -5px;
            }
 .col-md-4 {
    width: 33%;
  }

 nav {
     display: none !important;
 }


 ul, li {
     display: none !important;
 }

 .fluid-container{
     display: none !important;
 }
            }


            * {
                box-sizing: border-box;
                -moz-box-sizing: border-box;
            }




        </style>
    {% endblock custom_css %}

<div class="fluid-container">
    <nav class="navbar" id="nav">

        <ul class="navbar-nav">
            <!--  <li class="nav-item ">-->
            <!--  <a class="nav-link" href="#"><i class=" icon-2x icon-border fa fa-envelope icons-header" ></i></a>-->
            <!--</li>-->
            <li class="nav-item ">
                <a class="nav-link" href="javascript:history.back()"><i
                        class=" icon-2x icon-border icon-chevron-sign-left icons-header"></i></a>
            </li>

            <li class="nav-item">
                <form action="{% url 'set_language' %}" method="post" class="nav-link">{% csrf_token %}
                    {% get_current_language as LANGUAGE_CODE %}
                    <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                    {% if LANGUAGE_CODE == 'ar' %}
                        <button class="icon-border icons-header" style="font-size:15px" type='submit' name='language'
                                value='en'>
                            <span class="label"></span>English
                        </button>
                    {% else %}
                        <button class="icon-border icons-header" style="font-size:15px" type='submit' name='language'
                                value='ar'>
                            <span class="label"></span>عربي
                        </button>
                    {% endif %}
                </form>
            </li>

        </ul>

        <!--</div>-->
    </nav>
</div>
{% endblock %}

users/templates/menu1.html
{% load static %}

<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title> Settings</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<!-- <head>
 <meta charset="UTF-8">
 <title> Point Of Sale</title>
 <link rel="stylesheet" href="style.css">
 <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>  -->
<body>
{% block custom_css %}
    <style type="text/css" media="all">
        body {
            background-color: #fbfbfb;
            }
            @media (min-width: 991.98px) {
            main {
            padding-left: 240px;
            }
            }
            
            /* Sidebar */
            .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            padding: 58px 0 0; /* Height of navbar */
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
            width: 240px;
            z-index: 600;
            }
            
            @media (max-width: 991.98px) {
            .sidebar {
            width: 100%;
            }
            }
            .sidebar .active {
            border-radius: 5px;
            box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
            }
            
            .sidebar-sticky {
            position: relative;
            top: 0;
            height: calc(100vh - 48px);
            padding-top: 0.5rem;
            overflow-x: hidden;
            overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
            }


    </style>
{% endblock custom_css %}

<header class="navbar navbar-dark sticky-top bg-white flex-md-nowrap p-0 shadow" style="width: 100%; height: 55px">
    <img src="{% static 'images/Logo-TR.png' %}" alt="AdminLTE Logo"
         class="bi me-2 " style=" height: calc(calc(4.5rem + 3px) * .6);
      width: 16%; margin-left: 10px" style="position: fixed;">
{% include 'header.html' %}

    <a class="nav-link " id='dash' aria-current="page" href="{% url 'user:logout' %}" style="color: black">
                Logout
            </a>
</header>
<!--Main Navigation-->

    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a href="{% url 'user:dashboard_with_pivot' %}"  class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
            <i class="fa-solid fa-chart-line"></i><span> Main dashboard</span>
          </a>

          <a href="{% url 'client:client_list' %}" class="list-group-item list-group-item-action py-2 ripple active">
            <i class="fa-solid fa-users"></i><span> Clients</span>
          </a>

          <a href="{% url 'proposal:proposal_list' %}" class="list-group-item list-group-item-action py-2 ripple">
              <i class="nav-icon fas fa-edit"></i><span> Proposals</span></a>

          <a href="{% url 'contract:contract_list' %}" class="list-group-item list-group-item-action py-2 ripple"><i class="fa-solid fa-file-contract"></i><span> Contracts & Quotations</span></a>
         
          <a href="{% url 'project:project_list' %}" class="list-group-item list-group-item-action py-2 ripple">
            <i class="fa-solid fa-diagram-project"></i><span> Projects</span>
          </a>
          <a href="{% url 'project:task_list' %}" class="list-group-item list-group-item-action py-2 ripple"><i class="fa-solid fa-list-check"></i><span> Tasks</span></a>
         
          <a href="{% url 'document:document_list' %}" class="list-group-item list-group-item-action py-2 ripple"> <i class="fa-solid fa-file-contract"></i><span> Documents</span></a>
        
        </div>
      </div>
    </nav>
    <!-- Sidebar -->
  
   
       

         
  
         
        
  
 
</div>
</body>