Wakeel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    ]

urlpatterns += i18n_patterns(
    path('', include('clients.urls'), name='client'),
    path('', include('contracts.urls'), name='contract'),
    path('', include('documents.urls'), name='document'),
    path('', include('projects.urls'), name='project'),
    path('', include('proposals.urls'), name='proposal'),
    path('', include('users.urls'), name='user'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proposals/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import proposal_list, proposal_view, proposal_create, proposal_update, proposal_delete, \
    proposal_contract_create, pdf_generation_proposal

app_name = 'proposal'

urlpatterns = [

    path('proposal/list/', proposal_list, name='proposal_list'),
    path('proposal/view/<int:id>/', proposal_view, name='proposal_view'),
    path('proposal/create/', proposal_create, name='proposal_create'),
    path('proposal/update/<int:id>/', proposal_update, name='proposal_update'),
    path('proposal/delete/<int:id>/', proposal_delete, name='proposal_delete'),

    path('proposal/pdf/<int:id>', pdf_generation_proposal, name='proposal_pdf'),
    path('contract/proposal/<int:id>/', proposal_contract_create, name='proposal_contract_create'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import loginPage, logoutUser, dashboard_with_pivot, pivot_data

app_name = 'user'

urlpatterns = [
    # path('home/', dashboard, name='dashboard'),

    # path('register/', views.registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),

    # Password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_done.html"),
         name="password_reset_complete"),

    path('', dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', pivot_data, name='pivot_data'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proposals/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from clients.models import Client


class Proposal(models.Model):
    PROPOSAL_STATUS = (
        ('Delivered', 'Delivered'),
        ('Executed', 'Executed'),
        ('Pricing', 'Pricing')
    )
    proposal_id = models.CharField(max_length=255, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)
    proposal_status = models.CharField(max_length=255, choices=PROPOSAL_STATUS, null=True, blank=True)
    proposal_date = models.DateField(null=True, blank=True)
    proposal_amount = models.FloatField(null=True, blank=True)
    item_type = models.CharField(max_length=255, null=True, blank=True)
    no_items = models.CharField(max_length=255, null=True, blank=True)
    item_details = models.CharField(max_length=255, null=True, blank=True)
    img = models.ImageField(upload_to="images/", null=True, blank=True)
    es_width = models.FloatField(null=True, blank=True)
    es_height = models.FloatField(null=True, blank=True)
    fn_width = models.FloatField(null=True, blank=True)
    fn_height = models.FloatField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='create_proposal', null=True,
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='update_proposal', null=True,
                                   blank=True)
    updated_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)

proposals/forms.py
from django import forms
from django.core import validators
from .models import Proposal


class ProposalForm(forms.ModelForm):
    proposal_id = forms.CharField(validators=[validators.MinLengthValidator(4)],
                                  widget=forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                                "placeholder": "Enter Proposal ID"}), )

    class Meta:
        model = Proposal
        fields = ['proposal_id', 'proposal_status',
                  'proposal_amount', 'item_type', 'no_items',
                  'item_details', 'img', 'es_width', 'es_height', 'fn_width', 'fn_height',
                  'created_by', 'created_date', 'updated_by', 'updated_date']
        widgets = {
            'item_type': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                "placeholder": "Enter Item Type"}),
            'no_items': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                               "placeholder": "Enter No Items "}),
            'es_width': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                               "placeholder": "Enter ES Width"}),
            'es_height': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                "placeholder": "Enter Es Height "}),
            'fn_width': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                               "placeholder": "Enter Final Width "}),
            'fn_height': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                "placeholder": "Enter Final Height "}),
            'created_by': forms.Select(attrs={'class': 'regDropDown form-rounded',
                                                 "placeholder": "Enter Created BY "}),
            'updated_by': forms.Select(attrs={'class': 'regDropDown form-rounded form-rounded',
                                                 "placeholder": "Enter Updated BY "}),
            'proposal_status': forms.Select(attrs={'class': 'regDropDown form-rounded',

                                                        })
        }

    def clean_proposal_id(self):
        proposal_id = self.cleaned_data['proposal_id']
        if len(proposal_id) < 4:
            raise forms.ValidationError("Id must be 4 numbers")
        return proposal_id

    labels = {
        'proposal_id': 'Proposal-ID',
        'proposal_status': 'Proposal Status',
        'proposal_amount': 'Proposal Amount',
        'item_type': 'Item Type',
        'no_items': 'No Items',
        'item_details': 'Item Details',
        'img': 'Image',
        'es_width': 'ES Width',
        'es_height': 'Es Height',
        'fn_width': 'Fn Width',
        'fn_height': 'Fn Height',
        'created_by': 'Created By',
        'created_date': 'Created Date',
        'updated_by': 'Update By',
        'updated_date': 'Updated By'

    }

proposals/views.py
from clients.models import Client
from contracts.forms import ContractForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from users.decorators import allowed_users
from xhtml2pdf import pisa

from .forms import ProposalForm
from .models import Proposal


# Create your views here.

@login_required(login_url='user:login')
def proposal_list(request):
    context = {'proposal_list': Proposal.objects.all()}
    return render(request, "proposal/proposal_list.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_view(request, id):
    client_views = Client.objects.get(pk=id)
    proposal_view = get_object_or_404(Proposal, pk=id)
    context = {'proposal_view': proposal_view, 'client_views': client_views}
    return render(request, "proposal/proposal_view.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_create(request, id=0):
    if 'proposal_id' in request.POST and 'item_type' in request.POST and \
            'no_items' in request.POST and 'item_details' in request.POST and \
            'img' in request.POST and 'es_width' in request.POST and \
            'es_height' in request.POST and 'fn_width' in request.POST and \
            'fn_height' in request.POST and \
            'created_date' in request.POST and 'updated_date' in request.POST:

        proposal_id = request.POST['proposal_id']
        item_type = request.POST['item_type']
        no_items = request.POST['no_items']
        item_details = request.POST['item_details']
        img = request.POST['img']
        es_width = request.POST['es_width']
        es_height = request.POST['es_height']
        fn_width = request.POST['fn_width']
        fn_height = request.POST['fn_height']
        created_date = request.POST['created_date']
        updated_date = request.POST['updated_date']

    else:
        proposal_id = False
        item_type = False
        no_items = False
        item_details = False
        img = False
        es_width = False
        es_height = False
        fn_width = False
        fn_height = False
        created_date = False
        updated_date = False

    if request.method == "GET":
        if id == 0:
            form = ProposalForm()
        else:
            proposal = get_object_or_404(Proposal, pk=id)
            form = ProposalForm(instance=proposal)
        return render(request, "proposal/proposal_create.html", {'form': form})
    else:
        if request.method == "POST":
            if id == 0:
                form = ProposalForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('/proposal/list')


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_update(request, id):
    proposal = get_object_or_404(Proposal, pk=id)
    form = ProposalForm(instance=proposal)

    if request.method == 'POST':
        form = ProposalForm(request.POST, request.FILES, instance=proposal)
        if form.is_valid():
            form.save()
            return redirect('/proposal/list')

    return render(request, 'proposal/proposal_update.html', {'form': form})


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_delete(request, id):
    proposal = get_object_or_404(Proposal, pk=id)
    proposal.delete()
    return redirect('/proposal/list')


@login_required(login_url='user:login')
def pdf_generation_proposal(request, id):
    client_pdf = get_object_or_404(Client, pk=id)
    proposal_pdf = get_object_or_404(Proposal, pk=id)

    template_path = 'proposal/proposal_pdf.html'
    data = {
        "client_pdf": client_pdf, "proposal_pdf": proposal_pdf,

    }
    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template = get_template(template_path)

    html = template.render(data)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, encoding='UTF-8')
    # if error then show some fun view
    if pisa_status.err:
        return HttpResponse(html)
    return response


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_contract_create(request, id):
    contract_data = Proposal.objects.get(id=id)
    client_to_join = contract_data.client
    form = ContractForm(instance=contract_data)

    if request.method == 'POST':
        form = ContractForm(request.POST, request.FILES, initial={'contract_data': contract_data})
        if form.is_valid():
            proposal = Proposal.objects.get(pk=id)
            obj = form.save(commit=False)
            obj.proposal = proposal
            obj.save()

        return redirect('/contract/list')
    context = {'form': form, 'contract_data': contract_data, 'client': client_to_join}
    return render(request, 'contract/contract_create.html', context)

proposals/templates/proposal/proposal_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% block custom_css %}
        <style type="text/css">
            .form-rounded {
                border-radius: 1rem;
            }

        </style>
    {% endblock custom_css %}
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="col-12">
                <div class="card-header" style="background-color:#0B5ED7">
                    <h2 style="color:white">Proposal Create</h2>
                </div>
                <div class="card-body">
                </div>

                    <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label>Client ID: </label>
                                <input type="text" class="form-control form-rounded" value="{{ client.id }} " readonly>
                            </div>
                            <div class="col-md-4">
                                <label>ClientPersonal-ID :</label>
                                <input type="text" class="form-control form-rounded" value="{{ client.client_personal_id }}"
                                       readonly>

                            </div>
                            <div class="col-md-4">
                                <label>Client Name:</label>
                                <input type="text" class="form-control form-rounded" value="{{ client.client_name }}" readonly>
                            </div>
                            <div class="col-md-4">
                                <label>ClientHome-Tel :</label>
                                <input type="text" class="form-control form-rounded" value="{{ client.client_home_tel }}" readonly>
                            </div>
                            <div class="col-md-4">
                                <label>ClientOffice-Tel :</label>
                                <input type="text" class="form-control form-rounded" value="{{ client.client_office_tel }}" readonly>
                            </div>
                            <div class="col-md-4">
                                <label>Client Mobile :</label>
                                <input type="text" class="form-control form-rounded" value="{{ client.client_mobile }}" readonly>
                            </div>
                            <div class="col-md-8">
                                <label>Client Address :</label>
                                <input type="text" name="pos" class="form-control form-rounded" value="{{ client.client_address }},
{{ client.client_province }}, {{ client.client_nghood }}, {{ client.client_pobox }}"
                                       readonly>
                            </div>


                        </div>

                    </form>

            <br>

            <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">

                    <tbody>


                    <tr>
                        <td scope="row">
                            <input type="checkbox" name="check" id="check">
                        </td>
                         <td>
                                <label>Proposal ID: </label>
                                <input type="text" class="form-control form-rounded" name="proposal_id">
                            </td>

                                <td>
                                <label>Item Type: </label>
                                <input type="text" class="form-control form-rounded" name="item_type">
                            </td>

                                <td>
                                <label>Number Of Items: </label>
                                <input type="number" class="form-control form-rounded" name="no_items">
                            </td>

                                <td>
                                <label>Item Details: </label>
                                <input type="text" class="form-control form-rounded" name="item_details">
                            </td>

                                   <td>
                                <label>Design: </label>
                                <input type="file" class="form-control form-rounded" name="img">
                            </td>



                    </tr>

                    </tbody>
                </table>
                <table class="table">

                    <tbody>
                    <tr>
                        <td scope="row">
                            <input type="checkbox" name="check" id="check">
                        </td>

                                   <td>
                                <label>Estimated Width: </label>
                                <input type="number" class="form-control form-rounded" name="es_width">
                            </td>


                                   <td>
                                <label>Estimated Height: </label>
                                <input type="number" class="form-control form-rounded" name="es_height">
                            </td>


                                   <td>
                                <label>Final Width: </label>
                                <input type="number" class="form-control form-rounded" name="fn_width">
                            </td>

                          <td>
                                <label>Final Height: </label>
                                <input type="number" class="form-control form-rounded" name="fn_height">
                            </td>


                        <td>{{ form.proposal_status|as_crispy_field }}</td>


                    </tr>
                    </tbody>

                </table>
                <table class="table">

                    <tbody>
                    <tr>
                        <td scope="row"></td>
                        <td>{{ form.created_by|as_crispy_field }}</td>

                       <td> <label>Created Date: </label>

                            <input type="date" class="form-control form-rounded" name="created_date">
                    </td>
                            <td>{{ form.updated_by|as_crispy_field }}</td>
                                 <td>

                                <label>Updated Date: </label>
                                <input type="date" class="form-control form-rounded"  name="updated_date">
                            </td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="submit" class="btn btn-primary btn-block">
                        <i class="fa-solid fa-bookmark"></i>
                        save
                    </button>
                    &nbsp;
                    <a href="{% url 'proposal:proposal_list' %}" class="btn btn-primary btn-block float_right"><i
                            class="fa-solid fa-list"></i>

                        Back to list</a>
                </div>
                <div>
                </div>

            </form>
                </div>
            </div>
        </div>
    </main>


{% endblock content %}

proposals/templates/proposal/proposal_list.html
{% extends "base.html" %}

{% block content %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="col-12">
                <div class="card-header" style="background-color:#0B5ED7">

                    <h2 style="color:white">Proposal List</h2>
                </div>
                <br>
                <table class="table">
                    <thead style="background-color:#2072bb">
                    <tr class="col-10">
                        <th>
                            <input type="checkbox" name="check" id="check">
                        </th>
                        <th scope="col" style="color:white">Proposal-ID</th>
                        <th scope="col" style="color:white">Client-ID</th>
                        <th scope="col" style="color:white">Client Name</th>
                        <th scope="col" style="color:white">Proposal Date</th>
                        <th scope="col" style="color:white">Proposal Amount</th>
                        <th scope="col" style="color:white">Proposal Status</th>
                        <th scope="col" style="color:white">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for proposal in proposal_list %}
                        <tr>
                            <td scope="row">
                                <input type="checkbox" name="check" id="check">
                            </td>
                            <td>{{ proposal.proposal_id }}</td>
                            <td>{{ proposal.client_id }}</td>
                            <td>{{ proposal.client.client_name }}</td>
                            <td>{{ proposal.created_date }}</td>
                            <td>{{ proposal.proposal_amount }}</td>
                            <td>{{ proposal.proposal_status }}</td>
                            <td>
                                <a href="{% url 'proposal:proposal_update' proposal.id %}" class="btn text-secondary px-0">
                                    <i class="far fa-edit fa-lg"></i>
                                </a>

                                <a href="{% url 'proposal:proposal_view' proposal.id %}" class="btn text-secondary px-0">
                                    <i class="fas fa-eye fa-lg"></i>
                                </a>

                                <a href="{% url 'proposal:proposal_pdf' proposal.id %}" class="btn text-secondary px-0">
                                    <i class="fa-solid fa-file-pdf fa-lg"></i>
                                </a>

                                <form action="{% url 'proposal:proposal_delete' proposal.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn">
                                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>

                                    </button>
                                </form>
                                <a href="{% url 'proposal:proposal_contract_create' proposal.id %}"
                                   class="btn btn-outline-primary"
                                   style="float:right">
                                    <i class="fas fa-plus"></i>Add Contract
                                </a>
                            </td>


                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </main>

{% endblock content %}

proposals/templates/proposal/proposal_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
{% block custom_css %}
        <style type="text/css">
            .form-rounded {
                border-radius: 1rem;
            }

        </style>
    {% endblock custom_css %}
     <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<div class="col-12">
    <!-- enter div class="card" -->

            <div class="card-header" style="background-color:#0B5ED7">
               <h2 style="color:white">Proposal Update</h2>
            </div>

                <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-md-6">
                            {{form.item_type|as_crispy_field}}
                        </div>
                        <div class="col-md-6">
                            {{form.no_items|as_crispy_field}}
                        </div>
                        <div class="col-md-6">
                            {{form.es_width|as_crispy_field}}
                        </div>
                        <div class="col-md-6">
                            {{form.es_height|as_crispy_field}}
                        </div>
                        <div class="col-md-6">
                            {{form.fn_width|as_crispy_field}}
                        </div>
                        <div class="col-md-6">
                            {{form.fn_height|as_crispy_field}}
                        </div>
                         <div class="col-md-6">
                                    {{ form.created_by|as_crispy_field }}
                                </div>
                         <div class="col-md-6">
                                <label>Created Date: </label>
                                <input type="date" class="form-control form-rounded" name="created_date">
                                </div>
                                <div class="col-md-6">
                                    {{ form.updated_by|as_crispy_field }}
                                </div>


                                <div class="col-md-6">
                                <label>Updated Date: </label>
                                <input type="date" class="form-control form-rounded" name="updated_date">
                                </div>


                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button type="submit" class="btn btn-primary btn-block btn-lg"><i class="fa-solid fa-bookmark"></i>
                                        save</button>
                                        <a href="{% url 'proposal:proposal_list' %}" class="btn btn-primary btn-block btn-lg float_right"><i class="fa-solid fa-rectangle-xmark"></i>

                                            Cancel</a>
                                  </div>
                        </div>
            </form>

            </div>
            </div>


</main>

{% endblock content %}