Wakeel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    ]

urlpatterns += i18n_patterns(
    path('', include('clients.urls'), name='client'),
    path('', include('contracts.urls'), name='contract'),
    path('', include('documents.urls'), name='document'),
    path('', include('projects.urls'), name='project'),
    path('', include('proposals.urls'), name='proposal'),
    path('', include('users.urls'), name='user'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import project_list, project_view, project_create, project_update, project_delete, task_project_create, \
    pdf_generation_project, task_list, task_view, task_create, task_update, task_delete, pdf_generation_task

app_name = 'project'

urlpatterns = [

    path('project/list/', project_list, name='project_list'),
    path('project/view/<int:id>/', project_view, name='project_view'),
    path('project/create/', project_create, name='project_create'),
    path('project/update/<int:id>/', project_update, name='project_update'),
    path('project/delete/<int:id>/', project_delete, name='project_delete'),

    path('project/pdf/<int:id>', pdf_generation_project, name='project_pdf'),
    path('project/task/<int:id>/', task_project_create, name='task_project_create'),

    path('task/list/', task_list, name='task_list'),
    path('task/view/<int:id>/', task_view, name='task_view'),
    path('task/create/', task_create, name='task_create'),
    path('task/update/<int:id>/', task_update, name='task_update'),
    path('task/delete/<int:id>/', task_delete, name='task_delete'),

    path('task/pdf/<int:id>', pdf_generation_task, name='task_pdf'),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import loginPage, logoutUser, dashboard_with_pivot, pivot_data

app_name = 'user'

urlpatterns = [
    # path('home/', dashboard, name='dashboard'),

    # path('register/', views.registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),

    # Password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_done.html"),
         name="password_reset_complete"),

    path('', dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', pivot_data, name='pivot_data'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.contrib.auth.models import User
from django.db import models

from contracts.models import Contract


# Create your models here.

class Project(models.Model):
    PROJECT_STATUS = (
        ('A', 'A'),
        ('B', 'B'),
    )

    project_id = models.CharField(max_length=255, null=True, blank=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, related_name='contract_project', null=True,
                                 blank=True)
    project_name = models.CharField(max_length=255, null=True, blank=True)
    project_status = models.CharField(
        max_length=255, choices=PROJECT_STATUS, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    project_plan_delivery_date = models.DateField(null=True, blank=True)
    project_delivery_date = models.DateField(null=True, blank=True)
    contract_start_date = models.DateField(null=True, blank=True)
    contract_delivery_date = models.DateField(null=True, blank=True)
    sales = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='employee_sales')
    project_manager = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                        related_name='pj_manager_employee')
    item_type = models.CharField(max_length=255, null=True, blank=True)
    no_items = models.CharField(max_length=255, null=True, blank=True)
    item_details = models.CharField(max_length=255, null=True, blank=True)
    fn_width = models.FloatField(null=True, blank=True)
    fn_height = models.FloatField(null=True, blank=True)
    img = models.ImageField(upload_to="images/", null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='create_project', null=True,
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='update_project', null=True,
                                   blank=True)
    updated_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return self.project_name


class Task(models.Model):
    TASK_STATUS = (
        ('A', 'A'),
        ('B', 'B'),
    )

    task_id = models.CharField(max_length=255, null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True, related_name='task_project')

    sales_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name='task_sales_employee')
    project_manager_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                           related_name='task_pj_manager_employee')
    task_name = models.CharField(max_length=255, null=True, blank=True)
    item_type = models.CharField(max_length=255, null=True, blank=True)
    no_items = models.CharField(max_length=255, null=True, blank=True)
    item_details = models.CharField(max_length=255, null=True, blank=True)
    fn_width = models.FloatField(null=True, blank=True)
    fn_height = models.FloatField(null=True, blank=True)
    task_delivery_date = models.DateField(null=True, blank=True)
    task_status = models.CharField(max_length=255, choices=TASK_STATUS, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    img = models.ImageField(upload_to="images/", null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='create_task', null=True,
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return self.task_id

projects/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from django.template.loader import get_template
from xhtml2pdf import pisa
from clients.models import Client
from contracts.models import Contract
from projects.forms import ProjectForm
from projects.models import Project
from proposals.models import Proposal
from projects.forms import TaskFormSet
from projects.models import Task
from users.decorators import allowed_users
from projects.forms import TaskForm


# Create your views here.


@login_required(login_url='user:login')
def project_list(request):
    context = {'project_list': Project.objects.all()}
    return render(request, "project/project_list.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def project_view(request, id):
    project_view = get_object_or_404(Project, pk=id)
    # c = project_view.contract
    # print(c)
    # p = c.proposal
    # cl = p.client

    task_view = Task.objects.filter(Q(project__id=project_view.id))

    client_view = get_object_or_404(Client, pk=id)
    context = {'project_view': project_view, 'task_view': task_view,
               'client_view': client_view}
    return render(request, "project/project_view.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def project_create(request, id=0):
    if 'project_id' in request.POST and 'project_name' in request.POST and 'item_type' in request.POST and \
            'no_items' in request.POST and 'item_details' in request.POST and \
            'img' in request.POST and 'fn_width' in request.POST and \
            'fn_height' in request.POST and \
            'created_date' in request.POST and 'updated_date' in request.POST and 'end_date' in request.POST and \
            'project_plan_delivery_date' in request.POST and 'project_delivery_date' in request.POST:

        project_id = request.POST['project_id']
        project_name = request.POST['project_name']
        item_type = request.POST['item_type']
        no_items = request.POST['no_items']
        item_details = request.POST['item_details']
        img = request.POST['img']
        fn_width = request.POST['fn_width']
        fn_height = request.POST['fn_height']
        created_date = request.POST['created_date']
        updated_date = request.POST['updated_date']
        end_date = request.POST['end_date']
        project_plan_delivery_date = request.POST['project_plan_delivery_date']
        project_delivery_date = request.POST['project_delivery_date']

    else:
        project_id = False
        project_name = False
        item_type = False
        no_items = False
        item_details = False
        img = False
        fn_width = False
        fn_height = False
        created_date = False
        updated_date = False
        end_date = False
        project_plan_delivery_date = False
        project_delivery_date = False

    if request.method == "GET":
        if id == 0:
            form = ProjectForm()
        else:
            project = get_object_or_404(Project, pk=id)
            form = ProjectForm(instance=project)
        return render(request, "project/project_create.html", {'form': form})
    else:
        if request.method == "POST":
            if id == 0:
                form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('/project/list')


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def project_update(request, id):
    project = get_object_or_404(Project, pk=id)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('/project/list')

    return render(request, 'project/project_update.html', {'form': form})


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def project_delete(request, id):
    project = get_object_or_404(Project, pk=id)
    project.delete()
    return redirect('/project/list')


@login_required(login_url='user:login')
def pdf_generation_project(request, id):
    client_pdf = get_object_or_404(Client, pk=id)
    proposal_pdf = get_object_or_404(Proposal, pk=id)
    contract_pdf = get_object_or_404(Contract, pk=id)
    project_pdf = get_object_or_404(Project, pk=id)
    task_pdf = Task.objects.filter(Q(project__id=project_pdf.id))

    template_path = 'project/project_pdf.html'
    data = {
        "client_pdf": client_pdf, "proposal_pdf": proposal_pdf,
        "contract_pdf": contract_pdf, "project_pdf": project_pdf, "task_pdf": task_pdf

    }
    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template = get_template(template_path)

    html = template.render(data)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, encoding='UTF-8')
    # if error then show some fun view
    if pisa_status.err:
        return HttpResponse(html)
    return response


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def task_project_create(request, id):
    project_data = Project.objects.get(id=id)
    contract_to_join = project_data.contract
    proposal_to_join = contract_to_join.proposal
    client_to_join = contract_to_join.proposal.client
    initial = [{'project_data': project_data}]
    formset = TaskFormSet(queryset=Task.objects.none(), initial=initial)

    if request.method == 'POST':
        print(request.POST)
        formset = TaskFormSet(request.POST or None, request.FILES)
        if formset.is_valid():
            print(formset.is_valid())
            project = Project.objects.get(id=id)
            obj = formset.save(commit=False)
            for member in obj:
                member.project = project
                member.save()

            return redirect('/task/list')
    context = {'task_formset': formset, 'project_data': project_data, 'contract_to_join': contract_to_join,
               'proposal_to_join': proposal_to_join, 'client_to_join': client_to_join}
    return render(request, 'task/task_create.html', context)


@login_required(login_url='user:login')
def task_list(request):
    task_list = Task.objects.all()
    context = {'task_list': task_list}
    return render(request, "task/task_list.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def task_view(request, id):
    context = {'task_view': get_object_or_404(Task, pk=id)}
    return render(request, "task/task_view.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def task_create(request, id=0):
    # if 'task_id' in request.POST and 'task_name' in request.POST and 'item_type' in request.POST and \
    #         'no_items' in request.POST and 'item_details' in request.POST and \
    #         'img' in request.POST and 'fn_width' in request.POST and \
    #         'fn_height' in request.POST and 'task_delivery_date' in request.POST and \
    #         'end_date' in request.POST and 'created_date' in request.POST:
    #
    #     task_id = request.POST['task_id']
    #     task_name = request.POST['task_name']
    #     item_type = request.POST['item_type']
    #     no_items = request.POST['no_items']
    #     item_details = request.POST['item_details']
    #     img = request.POST['img']
    #     fn_width = request.POST['fn_width']
    #     fn_height = request.POST['fn_height']
    #     task_delivery_date = request.POST['task_delivery_date']
    #     end_date = request.POST['end_date']
    #     created_date = request.POST['created_date']
    #
    #
    # else:
    #     task_id = False
    #     task_name = False
    #     item_type = False
    #     no_items = False
    #     item_details = False
    #     img = False
    #     fn_width = False
    #     fn_height = False
    #     task_delivery_date = False
    #     end_date = False
    #     created_date = False

    if request.method == "GET":
        if id == 0:
            # TaskFormset = formset_factory(TaskForm,max_num=10,extra=1)
            formset = TaskFormSet(queryset=Task.objects.none())
        else:
            task = get_object_or_404(Task, pk=id)
            formset = TaskFormSet(queryset=Task.objects.none())
        return render(request, "task/task_create.html", {'task_formset': formset})
    else:
        if request.method == "POST":
            if id == 0:
                formset = TaskFormSet(request.POST, request.FILES)

        if formset.is_valid():
            formset.save()

        return redirect('/task/list')


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def task_update(request, id):
    task = get_object_or_404(Task, pk=id)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/task/list')

    return render(request, 'task/task_update.html', {'form': form})


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['projectmanager', 'admin'])
def task_delete(request, id):
    task = get_object_or_404(Task, id=id)
    task.delete()
    return redirect('/task/list')


@login_required(login_url='user:login')
def pdf_generation_task(request, id):
    client_pdf = get_object_or_404(Client, pk=id)
    project_pdf = get_object_or_404(Project, pk=id)
    contract_pdf = get_object_or_404(Contract, pk=id)
    task_pdf = get_object_or_404(Task, pk=id)

projects/templates/project/project_list.html
{% extends "base.html" %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="col-12">
            <div class="card-header" style="background-color:#0B5ED7">

                <h2 style="color:white">Project List</h2>
            </div>
            <br>
            <table class="table">
                <thead style="background-color:#2072bb">
                <tr class="col-10">
                    <th>
                        <input type="checkbox" name="check" id="check">
                    </th>
                    <th scope="col" style="color:white">Project-ID</th>
                    <th scope="col" style="color:white">Project Name</th>
                    <th scope="col" style="color:white">Project Status</th>
                    <th scope="col" style="color:white">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for project in project_list %}
                <tr>
                    <td scope="row">
                        <input type="checkbox" name="check" id="check">
                    </td>
                    <td>{{ project.project_id }}</td>
                    <td>{{ project.project_name }}</td>
                    <td>{{ project.project_status }}</td>

                    <td>
                        <a href="{% url 'project:project_update' project.id %}" class="btn text-secondary px-0">
                            <i class="far fa-edit fa-lg"></i>
                        </a>

                        <a href="{% url 'project:project_view' project.id %}" class="btn text-secondary px-0">
                            <i class="fas fa-eye fa-lg"></i>
                        </a>
                        <a href="{% url 'project:project_pdf' project.id %}" class="btn text-secondary px-0">
                            <i class="fa-solid fa-file-pdf fa-lg"></i>
                        </a>
                        <form action="{% url 'project:project_delete' project.id %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn">
                                <i class="far fa-trash-alt fa-lg text-danger float-right"></i>

                            </button>
                        </form>

                        <a href="{% url 'project:task_project_create' project.id %}" class="btn btn-outline-primary"
                           style="float:right">
                            <i class="fas fa-plus"></i>Add Task
                        </a>
                    </td>


                </tr>

                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

</main>

{% endblock content %}

projects/templates/project/project_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% block custom_css %}
<style type="text/css">
    .form-rounded {
        border-radius: 1rem;
    }

</style>
{% endblock custom_css %}
     <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <div class="col-12">
        <div class="card-header" style="background-color:#0B5ED7">
            <h2 style="color:white">Project View</h2>
        </div>
            <div class="card-body">
            </div>


            <div class="row">
                <div class="col-md-4">
                    <label>Project ID: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.id }} " readonly>
                </div>
                <div class="col-md-4">
                    <label>Contract ID: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.contract.id }} " readonly>
                </div>
                <div class="col-md-4">
                    <label>Client ID :</label>
                    <input type="text" class="form-control form-rounded" value="{{ client_view.id }}" readonly>

                </div>
                <div class="col-md-4">
                    <label>Project Name:</label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.project_name }}" readonly>
                </div>

                <div class="col-md-4">
                    <label>Project Planned Date :</label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.project_plan_delivery_date }}" readonly>
                </div>
                <div class="col-md-4">
                    <label>Project Status: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.project_status }} " readonly>
                </div>


                <div class="col-md-4">
                    <label>Project Start Date: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.start_date }} " readonly>
                </div>
                <div class="col-md-4">
                    <label>Project Delivery Date: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.project_delivery_date }} " readonly>
                </div>


                <div class="col-md-8">
                    <label>Client Address :</label>
                    <input type="text" name="pos" class="form-control form-rounded" value="{{ client_view.client_address }},
{{ client_view.client_province }}, {{ client_view.client_nghood }}, {{ client_view.client_pobox }}"
                           readonly>
                </div>

               
            </div>
            &nbsp


            <table class="table">
                            <thead style="background-color:#2072bb">
                            <tr class="col-10">
                                <th>
                                    <input type="checkbox" name="check" id="check">
                                </th>
                                <th scope="col" style="color:white">Task ID</th>
                                <th scope="col" style="color:white">Task Name</th>
                                <th scope="col" style="color:white">Task Delivery Date</th>
                                <th scope="col" style="color:white">Task Status</th>
                                <th scope="col" style="color:white">Actions</th>


            
                            </tr>
                            </thead>
            
                            <tbody>
       {% for task_view in task_view %}

                            <tr>

                                <td scope="row"></td>

                                <td>{{ task_view.id }}</td>
                                <td>{{ task_view.task_name }}</td>
                                <td>{{ task_view.task_delivery_date }}</td>
                                <td>{{ task_view.task_status }}</td>
                                <td>

                                    <a href="{% url 'project:task_update' task_view.id %}" class="btn text-secondary px-0">
                                        <i class="far fa-edit fa-lg"></i>
                                    </a>

                                    <a href="{% url 'project:task_view' task_view.id %}" class="btn text-secondary px-0">
                                        <i class="fas fa-eye fa-lg"></i>
                                    </a>

                                    <form action="{% url 'project:task_delete'  task_view.id %}" method="post" class="d-inline">
                                        {% csrf_token %}
                                        <button type="submit" class="btn">
                                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>

                                        </button>
                                    </form>

                                   
                                </td>



                            </tr>
                                           {%  endfor %}
                            </tbody>
                        </table>

                        



            <div class="row">
                <div class="col-md-4">
                    <label>Sales: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.sales }} " readonly>
                </div>
                <div class="col-md-4">
                    <label>Project Manager: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.project_manager }} " readonly>
                </div>
            </div>
            <div class="row">
            <div class="col-md-3">
                <label>Created Date: </label>
                <input type="text" class="form-control form-rounded" value="{{ project_view.created_date }} " readonly>
            </div>
                <div class="col-md-3">
                    <label>Created By: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.created_by }} " readonly>
                </div>
                <div class="col-md-3">
                    <label>Update Date: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.updated_date }} " readonly>
                </div>
                <div class="col-md-3">
                    <label>Updated By: </label>
                    <input type="text" class="form-control form-rounded" value="{{ project_view.updated_by }} " readonly>
                </div>
              
         
        </div>

    </div>
                </div>
</main>
{% endblock %}