Wakeel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    ]

urlpatterns += i18n_patterns(
    path('', include('clients.urls'), name='client'),
    path('', include('contracts.urls'), name='contract'),
    path('', include('documents.urls'), name='document'),
    path('', include('projects.urls'), name='project'),
    path('', include('proposals.urls'), name='proposal'),
    path('', include('users.urls'), name='user'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import client_list, client_view, client_create, client_update, \
    client_delete, proposal_client_create, pdf_generation_client

app_name = 'client'

urlpatterns = [

    path('client/list/', client_list, name='client_list'),
    path('client/view/<int:id>/', client_view, name='client_view'),
    path('client/create/', client_create, name='client_create'),
    path('client/update/<int:id>/', client_update, name='client_update'),
    path('client/delete/<int:id>/', client_delete, name='client_delete'),

    path('client/pdf/<int:id>', pdf_generation_client, name='client_pdf'),

    path('client/proposal/<int:id>/', proposal_client_create, name='proposal_client_create'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import loginPage, logoutUser, dashboard_with_pivot, pivot_data

app_name = 'user'

urlpatterns = [
    # path('home/', dashboard, name='dashboard'),

    # path('register/', views.registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),

    # Password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_done.html"),
         name="password_reset_complete"),

    path('', dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', pivot_data, name='pivot_data'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.

class Client(models.Model):
    client_name = models.CharField(max_length=200, null=True, blank=True)
    client_personal_id = models.CharField(max_length=30, null=True, blank=True)
    client_home_tel = models.CharField(max_length=15, null=True, blank=True)
    client_office_tel = models.CharField(max_length=15, null=True, blank=True)
    client_mobile = models.CharField(max_length=25, null=True, blank=True)
    client_address = models.CharField(max_length=500, null=True, blank=True)
    client_province = models.CharField(max_length=200, null=True, blank=True)
    client_nghood = models.CharField(max_length=300, null=True, blank=True)
    client_pobox = models.CharField(max_length=300, null=True, blank=True)
    contact_name = models.CharField(max_length=200, null=True, blank=True)
    contact_id = models.CharField(max_length=30, null=True, blank=True)
    contact_mobile = models.CharField(max_length=25, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='create_client', null=True,
                                   blank=True)
    updated_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='update_client', null=True,
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=False, null=True, blank=True)

    def __str__(self):
        return self.client_name

clients/forms.py
from django import forms
from django.core import validators

from clients.models import Client
from django.utils.translation import gettext_lazy as _


class ClientForm(forms.ModelForm):
    # client_name = forms.CharField(label=_(u'Client Name'),
    #                               widget=forms.TextInput(attrs={'class': 'form-control form-rounded',
    #                                                             "placeholder": "Enter Client Name"}))
    # client_personal_id = forms.CharField(label=_(u'Client Personal-ID'))
    # client_home_tel = forms.CharField(label=_('Client Home Telephone'))

    client_personal_id = forms.CharField(validators=[validators.MinLengthValidator(4)],
                                         widget=forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                                       "placeholder": "Enter Client Personal ID"}))

    class Meta:
        model = Client
        fields = ['client_name', 'client_personal_id', 'client_home_tel', 'client_office_tel', 'client_mobile',
                  'client_address', 'client_province', 'client_nghood', 'client_pobox',
                  'contact_name', 'contact_id', 'contact_mobile',
                  'created_by', 'created_date',
                  'updated_by', 'updated_date']
        widgets = {
            'client_name': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                  }),
            'client_home_tel': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                      }),
            'client_office_tel': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                        }),
            'client_mobile': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                    }),
            'client_address': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                     }),
            'client_province': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                      }),
            'client_nghood': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                    }),
            'client_pobox': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                   }),
            'contact_name': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                   }),
            'contact_id': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                 }),
            'contact_mobile': forms.TextInput(attrs={'class': 'form-control form-rounded',
                                                     }),
            'created_by': forms.Select(attrs={'class': 'regDropDown form-rounded form-rounded',
                                              }),
            'created_date': forms.Select(attrs={'class': 'regDropDown form-rounded',
                                                }),
            'updated_by': forms.Select(attrs={'class': 'regDropDown form-rounded form-rounded',
                                              }),

        }

    def clean_personal_id(self):
        client_personal_id = self.cleaned_data['client_personal_id']
        contact_id = self.cleaned_data['contact_id']

        if len(client_personal_id) < 4 and len(contact_id) < 4:
            raise forms.ValidationError("Id must be 8 numbers")
        return client_personal_id, contact_id

    # labels = {
    #     'client_name': 'Client Name',
    #     'client_personal_id': 'ClientPersonal-ID',
    #     'client_home_tel': 'ClientHome-Tel',
    #     'client_office_tel': 'ClientOffice-Tel',
    #     'client_mobile': 'Client Mobile',
    #     'client_address': 'Client Address',
    #     'client_province': 'Client Province',
    #     'client_nghood': 'Client NGhood',
    #     'client_pobox': 'Client PoBox',
    #     'contact_name': 'Contact Name',
    #     'contact_id': 'Contact-PID',
    #     'contact_mobile': 'Contact Mobile',
    #     'created_by': 'Created By',
    #     'created_date': 'Created Date',
    #     'updated_by': 'Update By',
    #     'updated_date': 'Updated By'
    #
    # }

clients/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from clients.forms import ClientForm
from clients.models import Client
from proposals.forms import ProposalForm
from proposals.models import Proposal
from users.decorators import allowed_users
from xhtml2pdf import pisa


# Create your views here.

@login_required(login_url='user:login')
def client_list(request):
    context = {'client_list': Client.objects.all()}
    return render(request, "clients/client_list.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def client_view(request, id):
    proposal_views = Proposal.objects.get(pk=id)
    context = {'client_view': get_object_or_404(Client, pk=id), 'proposal_views': proposal_views}
    return render(request, "clients/client_view.html", context)


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def client_create(request, id=0):
    if 'client_name' in request.POST and 'client_personal_id' in request.POST and 'client_home_tel' in request.POST and \
            'client_office_tel' in request.POST and 'client_mobile' in request.POST and 'client_address' in request.POST and \
            'client_province' in request.POST and 'client_nghood' in request.POST and 'client_pobox' in request.POST and \
            'contact_name' in request.POST and 'contact_id' in request.POST and 'contact_mobile' in request.POST and \
            'updated_date' in request.POST and 'created_date' in request.POST:

        client_name = request.POST['client_name']
        client_personal_id = request.POST['client_personal_id']
        client_home_tel = request.POST['client_home_tel']
        client_office_tel = request.POST['client_office_tel']
        client_mobile = request.POST['client_mobile']
        client_address = request.POST['client_address']
        client_province = request.POST['client_province']
        client_nghood = request.POST['client_nghood']
        client_pobox = request.POST['client_pobox']
        contact_name = request.POST['contact_name']
        contact_id = request.POST['contact_id']
        contact_mobile = request.POST['contact_mobile']
        created_date = request.POST['created_date']
        updated_date = request.POST['updated_date']

    else:
        client_name = False
        client_personal_id = False
        client_home_tel = False
        client_office_tel = False
        client_mobile = False
        client_address = False
        client_province = False
        client_nghood = False
        client_pobox = False
        contact_name = False
        contact_id = False
        contact_mobile = False
        created_date = False
        updated_date = False

    if request.method == "GET":
        if id == 0:
            form = ClientForm()
        else:
            client = get_object_or_404(Client, pk=id)
            form = ClientForm(instance=client)
        return render(request, "clients/client_create.html", {'form': form})
    else:
        if request.method == "POST":
            if id == 0:
                form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('/client/list')


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def client_update(request, id):
    client = Client.objects.get(pk=id)
    form = ClientForm(instance=client)

    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()

            return redirect('/client/list')

    return render(request, 'clients/client_update.html', {'form': form})


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def client_delete(request, id):
    client = get_object_or_404(Client, pk=id)
    client.delete()
    return redirect('/client/list')


def pdf_generation_client(request, id):
    client_pdf = get_object_or_404(Client, pk=id)
    proposal_pdf = get_object_or_404(Proposal, pk=id)

    template_path = 'clients/client_pdf.html'
    data = {
        "client_pdf": client_pdf, "proposal_pdf": proposal_pdf,

    }
    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template = get_template(template_path)

    html = template.render(data)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, encoding='UTF-8')
    # if error then show some fun view
    if pisa_status.err:
        return HttpResponse(html)
    return response


@login_required(login_url='user:login')
@allowed_users(allowed_roles=['sales', 'admin'])
def proposal_client_create(request, id):
    client = Client.objects.get(pk=id)
    form = ProposalForm(instance=client)
    if request.method == 'POST':
        form = ProposalForm(request.POST, request.FILES,
                            initial={'client': client})
        if form.is_valid():
            client = Client.objects.get(pk=id)
            obj = form.save(commit=False)
            obj.client = client
            obj.save()
            return redirect('/proposal/list')
    context = {'form': form, 'client': client}
    return render(request, 'proposal/proposal_create.html', context)

clients/templates/clients/client_create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
    {% block custom_css %}
        <style type="text/css">
            .form-rounded {
                border-radius: 1rem;
            }

        </style>
    {% endblock custom_css %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="col-12">
                <div class="card-header" style="background-color:#0B5ED7">
                    <h2 style="color:white">Client Create</h2>
                </div>
                <div class="card-body">

                </div>

                <form role="form" action="" method="post" autocomplete="off" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        <thead style="background-color:#2072bb">

                        <tbody>

                        <tr>
                            <td scope="row">
                                <input type="checkbox" name="check" id="check">
                            </td>
                            <td>
                                <label>Client Name:</label>
                                <input type="text" class="form-control form-rounded" name="client_name" >
                            </td>
                               <td>
                                <label>Client Personal ID: </label>
                                <input type="text" class="form-control form-rounded" name="client_personal_id">
                            </td>

                                    <td>
                                <label>Client Home Telephone: </label>
                                <input type="text" class="form-control form-rounded" name="client_home_tel">
                            </td>

                                <td>
                                <label>Client Office Telephone: </label>
                                <input type="text" class="form-control form-rounded" name="client_office_tel">
                            </td>

                                        <td>
                                <label>Client Mobile: </label>
                                <input type="text" class="form-control form-rounded" name="client_mobile">
                            </td>


                        </tr>

                        </tbody>
                    </table>

                    <table class="table">

                        <tbody>
                        <tr>
                            <td scope="row">
                                <input type="checkbox" name="check" id="check">
                            </td>
                             <td>
                                <label>Client Address: </label>
                                <input type="text" class="form-control form-rounded" name="client_address">
                            </td>
                                 <td>
                                <label>Client Province: </label>
                                <input type="text" class="form-control form-rounded" name="client_province">
                            </td>
             <td>
                                <label>Client Neighborhood: </label>
                                <input type="text" class="form-control form-rounded" name="client_nghood">
                            </td>

                                      <td>
                                <label>Client Phone-Box: </label>
                                <input type="text" class="form-control form-rounded" name="client_pobox">
                            </td>



                        </tr>
                        </tbody>
                    </table>

                    <table class="table">

                        <tbody>
                        <tr>
                            <td scope="row">
                                <input type="checkbox" name="check" id="check">
                            </td>

                              <td>
                                <label>Contact Name: </label>
                                <input type="text" class="form-control form-rounded" name="contact_name">
                            </td>

                             <td>
                                <label>Contact ID: </label>
                                <input type="text" class="form-control form-rounded" name="contact_id">
                            </td>

                                    <td>
                                <label>Contact Mobile: </label>
                                <input type="text" class="form-control form-rounded" name="contact_mobile">
                            </td>


                        </tr>
                        </tbody>

                    </table>

                    <table class="table">

                        <tbody>
                        <tr>
                            <td scope="row"></td>

                            <td>{{ form.created_by|as_crispy_field }}</td>

                            <td>
                                <label>Created Date: </label>
                                <input type="date" class="form-control form-rounded" name="created_date">
                            </td>

                            <td>{{ form.updated_by|as_crispy_field }}</td>

                            <td>
                                <label>Updated Date: </label>
                                <input type="date" class="form-control form-rounded" name="updated_date">
                            </td>

                        </tr>
                        </tbody>
                    </table>
                    <br>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button type="submit" class="btn btn-primary btn-block btn-lg">
                            <i class="fa-solid fa-bookmark"></i>
                            save
                        </button>
                        &nbsp;
                        <a href="{% url 'client:client_list' %}" class="btn btn-primary btn-block btn-lg float_right"><i
                                class="fa-solid fa-list"></i>

                            Back to list</a>
                    </div>
                </form>
            </div>

        </div>

    </main>

{% endblock content %}

clients/templates/clients/client_list.html
{% extends "base.html" %}
{% block content %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="col-12">
                <div class="card-header" style="background-color:#0B5ED7">
                    <a href="{% url 'client:client_create' %}" class="btn btn-light" style="float:right">
                        <i class="fas fa-plus"></i>Add New
                    </a>

                    <h2 style="color:white">Client List</h2>
                </div>
                <br>
                <table class="table">
                    <thead style="background-color:#2072bb">
                    <tr class="col-10">
                        <th>
                            <input type="checkbox" name="check" id="check">
                        </th>
                        <th scope="col" style="color:white">Client Name</th>
                        <th scope="col" style="color:white">Client Personal-ID</th>
                        <th scope="col" style="color:white">Client Home-Tel</th>
                        <th scope="col" style="color:white">Client Office-Tel</th>
                        <th scope="col" style="color:white">Client Mobile</th>
                        <th scope="col" style="color:white">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for client in client_list %}
                        <tr>
                            <td scope="row">
                                <input type="checkbox" name="check" id="check">
                            </td>
                            <td>{{ client.client_name }}</td>
                            <td>{{ client.client_personal_id }}</td>
                            <td>{{ client.client_home_tel }}</td>
                            <td>{{ client.client_office_tel }}</td>
                            <td>{{ client.client_mobile }}</td>
                            <td>
                                <a href="{% url 'client:client_update' client.id %}" class="btn text-secondary px-0">
                                    <i class="far fa-edit fa-lg"></i>
                                </a>


                                <a href="{% url 'client:client_view' client.id %}" class="btn text-secondary px-0">
                                    <i class="fas fa-eye fa-lg"></i>
                                </a>
                                <a href="{% url 'client:client_pdf' client.id %}" class="btn text-secondary px-0">
                                    <i class="fa-solid fa-file-pdf fa-lg"></i>
                                </a>
                                <form action="{% url 'client:client_delete' client.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn">
                                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>

                                    </button>
                                </form>

                                <a href="{% url 'client:proposal_client_create' client.id %}" class="btn btn-outline-primary"
                                   style="float:right">
                                    <i class="fas fa-plus"></i>Add Proposal
                                </a>
                            </td>


                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>

{% endblock content %}

clients/templates/clients/client_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
    {% block custom_css %}
        <style type="text/css">
            .form-rounded {
                border-radius: 1rem;
            }

        </style>
    {% endblock custom_css %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <div class="col-12">
                <!-- enter div class="card" -->
                <div class="card-header" style="background-color:#0B5ED7">
                    <h2 style="color:white">Client Update</h2>
                </div>
                <div class="card-body">
                </div>


                <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-md-5">
                            {{ form.client_name|as_crispy_field }}
                        </div>

                        <div class="col-md-5">
                            {{ form.client_personal_id|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_home_tel|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_office_tel|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_mobile|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_address|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_province|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_nghood|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.client_pobox|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.contact_name|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.contact_id|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.contact_mobile|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.created_by|as_crispy_field }}
                        </div>
                        <div class="col-md-5">
                            {{ form.updated_by|as_crispy_field }}
                        </div>

<!--                        <div class="col-md-5">-->
<!--                            {{ form.created_date|as_crispy_field }}-->
<!--                        </div>-->
  <div class="col-md-5">
                            <label>Created Date: </label>
                            <input type="date" class="form-control form-rounded" name="created_date">
                        </div>
                        <div class="col-md-5">
                            <label>Updated Date: </label>
                            <input type="date" class="form-control form-rounded" name="updated_date">
                        </div>


                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <button type="submit" class="btn btn-primary btn-block btn-lg"><i
                                    class="fa-solid fa-bookmark"></i>
                                save
                            </button>
                            <a href="{% url 'client:client_list' %}"
                               class="btn btn-primary btn-block btn-lg float_right"><i
                                    class="fa-solid fa-rectangle-xmark"></i>

                                Cancel</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>


    </main>

{% endblock content %}